export function getRandomTopic() {
  return randomTopics[Math.floor(Math.random() * randomTopics.length)];
}

export function getRandomOptions() {
  return randomOptions[Math.floor(Math.random() * randomOptions.length)];
}

const randomTopics = [
  "Ice cubes",
  "A microwave",
  "The sun",
  "A paperclip",
  "Duct tape",
  "A library",
  "A roller coaster",
  "The Beatles",
  "Avocado toast",
  "A fast food burger",
  "A private jet",
  "A library whisper",
  "A rock concert",
  "The pyramids",
  "A smartphone",
  "A tuxedo",
  "A warm blanket",
  "A diamond",
  "A snail",
  "A Ferrari",
  "A lion",
  "A mouse",
  "A rainy day",
  "A birthday party",
  "A cardboard box",
  "A skyscraper",
  "A goldfish",
  "The internet",
  "A handwritten letter",
  "A neon sign",
  "A sleeping puppy",
  "Coffee",
  "A campfire",
  "A wild tiger",
  "A broken umbrella",
  "A bottle of wine",
  "A marathon",
  "A crossword puzzle",
  "A superhero",
  "A used car",
  "A luxury watch",
  "A kindergarten",
  "A university",
  "A secret",
  "A crowded street",
  "A desert",
  "A rainforest",
  "A volcano",
  "A telescope",
  "A microscope",
  "A heavy metal song",
  "A lullaby",
  "A pizza",
  "A salad",
  "A toothbrush",
  "A master's degree",
  "A lottery win",
  "A flat tire",
  "A rainbow",
  "A lemon",
  "Honey",
  "A ghost",
  "A professional athlete",
  "A toddler",
  "A spacesuit",
  "A medieval sword",
  "A plastic fork",
  "A mountain",
  "A pebble",
  "A selfie",
  "A classic novel",
  "A TikTok dance",
  "A black hole",
  "The moon",
  "A frozen lake",
  "A rubber duck",
  "A shark",
  "A dandelion",
  "A gold medal",
  "A garbage can",
  "A velvet rope",
  "A wifi password",
  "A compass",
  "A map",
  "A dictionary",
  "A comic book",
  "A symphony",
  "A meme",
  "A vintage camera",
  "A drone",
  "A polar bear",
  "A cactus",
  "A cupcake",
  "A brick",
  "A feather",
  "A stopwatch",
  "A calendar",
  "A mirror",
  "A double espresso",
  "An electric toothbrush",
  "A camouflage jacket",
  "Yoga pants",
  "The newest iPhone",
  "A porcelain doll",
  "Winning the lottery",
  "A local bakery",
  "A saltwater aquarium",
  "Elvis Presley",
  "A hermit crab",
  "A philosophy book",
  "A spreadsheet",
  "A tailored suit",
  "A wooden chair",
  "A solar panel",
  "A firefighter",
  "The life of a fly",
  "Ziploc bags",
  "The Mona Lisa",
  "A Jenga tower",
  "A drill sergeant",
  "New York City",
  "A venomous snake",
  "The weather in 1994",
  "A child's drawing",
  "A yellow balloon",
  "A white room",
  "A floppy disk",
  "A megaphone",
  "Cold pizza",
  "The Opera",
  "A brain surgeon",
  "A peacock",
  "A river",
  "A paper plate",
  "A VIP pass",
  "A plot hole",
  "A Greek god",
  "Dark chocolate",
  "A rough sketch",
  "A broken elevator",
  "A weighted blanket",
  "A hula hoop",
  "A monk",
  "A lucky penny",
  "A laser pointer",
  "A ballerina",
  "A magic trick",
  "A garbage truck",
  "A wolf",
  "A deep sea trench",
  "A Nobel Prize",
  "A wink",
  "A board game",
  "An eclipse",
  "A sandcastle",
  "A puppy",
  "An ant farm",
  "A biography",
  "A spam email",
  "A concrete wall",
  "A magnet",
  "Glacier movement",
  "A sponge",
  "A cottage",
  "Winning a race",
  "A side quest",
  "A sports car",
  "A surprise party",
  "A farm",
  "A bank",
  "A swear word",
  "A math proof",
  "A hot water bottle",
  "A fossil",
  "A panda",
  "A tip jar",
  "A secret handshake",
  "A toothpick",
  "The Great Wall",
  "A fireworks display",
  "A stop sign",
  "A sunset",
  "A heavy rock",
  "A plastic bottle",
  "A black cat",
  "A knight",
  "A courtroom",
  "A clockwork",
  "A small gesture",
  "A grandmaster",
  "Air",
  "A backpack",
  "A vampire",
  "The Rocky Horror Picture Show",
  "A polaroid camera",
  "Chicken soup",
  "Britney Spears",
  "A local indie band",
  "A porcelain doll with cracks",
  "Avengers: Endgame",
  "Quantum physics",
  "A puppy that chewed a shoe",
  "A deadline in 1 hour",
  "A new crypto coin",
  "The Godfather",
  "A roller coaster ride",
  "Vinyl records",
  "A typewriter",
  "Wednesday Addams",
  "The ability to change hair color",
  "A fruit fly",
  "E.T.",
  "Titanic",
  "A farmhouse",
  "A room full of neon signs",
  "Salted caramel",
  "A taco truck",
  "A toddler eating spaghetti",
  "A beach umbrella",
  "A coffee machine at 6 AM",
  "A professional gamer",
  "A captain of a ship",
  "An inventor",
  "Buying groceries",
  "Saving the world from an asteroid",
  "The Hunger Games",
  "The Lord of the Rings",
  "A Picasso painting",
  "A mime",
  "A drill sergeant father",
  "Romeo and Juliet",
  "A couple holding hands after 50 years",
  "A penthouse in NYC",
  "Stardew Valley",
  "A coal miner",
  "A small cafe in a back alley",
  "A crowded bus",
  "A dusty library book",
  "A grayscale photo",
  "Charlie Chaplin",
  "Avatar (2009)",
  "A TikTok trend",
  "A glass of lemonade",
  "An apple",
  "A homemade lasagna",
  "A bag of gummy bears",
  "Boiled potatoes",
  "Someone playing Candy Crush",
  "A high-end PC",
  "A 2005 internet connection",
  "Red Dead Redemption 2",
  "A local server",
  "A solo hiker",
  "A fast food worker",
  "Elon Musk",
  "A data entry job",
  "Talking about the weather",
  "A 2-hour long phone call",
  "Leaving a message on read",
  "An engagement ring",
  "Someone you pass on the street",
  "A black cat crossing the road",
  "Harry Potter",
  "Robin from Batman",
  "Michael Jordan",
  "A retired soldier",
  "Drink more water",
  "The sky is blue",
  "A password written on a sticky note",
  "A celebrity sighting",
  "Gravity",
  "A Christmas gift from grandma",
  "A Gucci bag",
  "Air Jordans",
  "Waking up on a Sunday",
  "A wedding dress",
  "A tiger",
  "C-3PO",
  "Harry Potter's wand",
  "Dracula",
  "A haunted house",
  "The Exorcist",
  "A stand-up special",
  "A cowboy on a horse",
  "Spirited Away",
  "The Joe Rogan Experience",
  "An anonymous donation",
  "The Pyramids of Giza",
  "Telling a kid Santa is real",
  "A perfectly packed suitcase",
  "A religious text",
  "Flat Earth theory",
  "A child wearing 3 helmets",
  "A golden toilet",
  "A soap bubble",
  "A monk in meditation",
  "A high school football star",
  "Astrology",
  "A prisoner released early",
  "A dream you forget instantly",
  "A zen garden",
  "Saying 'it's fine' during a fire",
  "A legal contract",
  "A Walkman",
  "Playing rock-paper-scissors",
  "A professional assassin",
  "A street performer",
  "Coco Chanel",
  "Leaving a dirty dish in the sink to 'soak'",
  "A grandma's critique",
  "A person in a suit at a rave",
  "Eating a whole cake alone",
  "Dividing the CDs after a divorce",
  "Singing perfectly in the shower",
  "A surprise party for 100 people",
  "A tabloid headline",
  "A library in an old mansion",
  "A 1-dollar toy",
  "A knitted sweater",
  "An exposed brick wall",
  "A weed growing through concrete",
  "No jaywalking",
  "Public nudity",
  "A rainy Monday morning",
  "A movie where everyone lives happily ever after",
  "A UFO hunter",
  "Unseasoned tofu",
  "A durian fruit",
  "Sandpaper",
  "A lead pipe",
  "A lighthouse beam",
  "A 10-season TV show",
  "A teenager's bedroom",
  "A child's mud pie",
  "A black cat crossing your path",
  "Winning at poker",
  "A beige cardigan",
  "Las Vegas",
  "Betting your house on red",
  "A 5-year-old who loves jazz",
  "Stealing a grape from the store",
  "The 100th ranked tennis player",
  "The World Cup",
  "A single sock",
  "A person with heterochromia",
  "Watergate",
  "British dry comedy",
  "Olives",
  "Graduating after 10 years",
  "A person who talks about their diet constantly",
  "A lioness hunting",
  "A blurry Bigfoot sighting",
  "Calligraphy",
  "A library sign",
  "Inception",
  "A PhD in underwater basket weaving",
  "A rocket scientist",
  "A Yoda-like figure",
  "A cubicle",
  "Working 100 hours a week",
  "Marvel movies",
  "Posting a gym selfie",
  "A VPN",
  "Banksy",
  "A leaked government document",
  "A vinyl record player",
  "Finding a 20-dollar bill on the street",
  "A truce during a card game",
  "A judge",
  "Helping an old lady cross the street",
  "Missing the bus by 1 second",
  "A shooting star",
  "A politician's speech",
  "A billionaire's tip",
  "A 40-year-old buying a red Ferrari",
  "The reality of a surgery",
  "A trash bag",
  "Deadpool",
  "Finding a rare collectible",
  "A priest in a booth",
  "Eating pizza with a fork",
  "White lies",
  "Universal Basic Income",
  "Putting a bucket on someone's head",
  "Kanye West",
  "Using big words incorrectly",
  "A child prodigy who quit",
  "Ghosting after one date",
  "A professional gamer's salary",
  "A billionaire donating to a library",
  "Cameras in every street corner",
  "A 9 PM curfew for everyone",
  "Splitting the bill on a first date",
  "Wearing a onesie in public",
  "A banana taped to a wall",
  "The Kardashians",
  "Accidentally liking an ex's photo",
  "Telling someone their baby is ugly",
  "Encryption on phones",
  "Replacing books with tablets",
  "The movie 'Interstellar'",
  "Bungee jumping without a helmet",
  "Staying in bed all Sunday",
  "Wearing pajamas to a funeral",
  "A gold-plated iPhone",
  "The French Revolution",
  "A quote about stars and souls",
  "Card counting in blackjack",
  "A 50-page terms of service",
  "Rescuing a cat for the Instagram photo",
  "A movie about 1700s with 2024 slang",
  "A 1000-dollar skincare routine",
  "Watching reality TV to relax",
  "Taking away a kid's phone for a month",
  "Thinking you'll win the lottery tomorrow",
  "Checking your partner's phone",
  "Wearing a wizard hat daily",
  "Quiet quitting",
  "Winning a talent show because of a sad story",
  "A CEO's son getting a VP job",
  "Agreeing with everyone in the room",
  "Refusing to lend money to family",
  "Talking about yourself in the third person",
  "Rating a restaurant 1 star for a long wait",
  "Paparazzi photos",
  "A 'Live, Laugh, Love' sign",
  "Giving someone a vacuum cleaner for their wedding",
  "Saying 'Santa is busy' to a crying kid",
  "Gender reveal parties",
  "Showing up to a party 3 hours early",
  "Booking a flight 1 hour before takeoff",
  "Following a leader into a volcano",
  "A 40-year-old still living in their childhood bedroom",
  "Batman",
  "Letting a thief go because they were hungry",
  "Smiling at everyone on the subway",
  "A 10-year plan for world domination",
  "Trackers on a teenager's phone",
  "A controversial comedian",
  "A blank canvas in a museum",
  "A boy band formed by a corporation",
  "A poem written by ChatGPT",
  "A celebrity driving a Prius",
  "Living in a van by choice",
  "A private cinema in a house",
  "A secret club with a 10-year waitlist",
  "An internet forum for one specific brand",
  "A protest where people glue themselves to roads",
  "A house with no furniture",
  "Petting a stray lion",
  "A doctor with no bedside manner",
  "Wearing flip-flops to the office",
  "Telling a coworker their idea is bad",
  "Changing your mind every 5 minutes",
  "Being a librarian",
  "A mandatory school uniform",
  "Cloning a pet",
  "Family gatherings every Sunday",
  "Flags on every house",
  "Starting a business in a garage",
  "An eye for an eye",
  "Giving up a kidney for a stranger",
  "A diary with a lock",
  "Asking someone's salary",
  "Having 5000 houseplants",
  "Mickey Mouse",
  "Bell-bottom jeans",
  "The NFT craze",
  "A 5-dollar watch",
  "A progressive tax system",
  "Free healthcare",
  "A documentary film",
  "Advice from a 90-year-old",
  "A commercial with a diverse cast",
  "A 'Limited Edition' label on soda",
  "Bottled water from a tap",
  "A CEO who fires everyone via Zoom",
  "A Twitter mob",
  "Cyberpunk 2077",
];

const randomOptions = [
  ["Bad", "Good"],
  ["Cold", "Hot"],
  ["Big", "Small"],
  ["Useful", "Useless"],
  ["Boring", "Exciting"],
  ["Overrated", "Underrated"],
  ["Healthy", "Unhealthy"],
  ["Cheap", "Expensive"],
  ["Loud", "Quiet"],
  ["New", "Old"],
  ["Modern", "Traditional"],
  ["Strong", "Weak"],
  ["Hard", "Soft"],
  ["Fast", "Slow"],
  ["Dangerous", "Safe"],
  ["Classy", "Trashy"],
  ["Beautiful", "Ugly"],
  ["Kind", "Mean"],
  ["Dull", "Shiny"],
  ["Extrovert", "Introvert"],
  ["Cool", "Uncool"],
  ["Large-scale", "Small-scale"],
  ["Long-lasting", "Short-lived"],
  ["Fake", "Real"],
  ["Happy", "Sad"],
  ["Objective", "Subjective"],
  ["Mainstream", "Niche"],
  ["Predictable", "Unpredictable"],
  ["Encouraged", "Forbidden"],
  ["Brilliant", "Stupid"],
  ["Durable", "Fragile"],
  ["Casual", "Formal"],
  ["Complex", "Simple"],
  ["Heavy", "Light"],
  ["Dry", "Wet"],
  ["Fancy", "Plain"],
  ["Common", "Rare"],
  ["Immature", "Mature"],
  ["High quality", "Low quality"],
  ["Futuristic", "Historical"],
  ["Actually good", "Guilty pleasure"],
  ["Important", "Insignificant"],
  ["Ethical", "Unethical"],
  ["Amateur", "Professional"],
  ["Permanent", "Temporary"],
  ["Famous", "Obscure"],
  ["Clean", "Messy"],
  ["Popular", "Unpopular"],
  ["Aggressive", "Passive"],
  ["Selfish", "Selfless"],
  ["Brave", "Cowardly"],
  ["Relaxed", "Strict"],
  ["Artificial", "Natural"],
  ["Lucky", "Unlucky"],
  ["Forgettable", "Iconic"],
  ["Bitter", "Sweet"],
  ["High calorie", "Low calorie"],
  ["Dark", "Light"],
  ["Rough", "Smooth"],
  ["Big brain", "Small brain"],
  ["High stakes", "Low stakes"],
  ["Bad smell", "Good smell"],
  ["Narrow", "Wide"],
  ["For adults", "For kids"],
  ["Hero", "Villain"],
  ["Funny", "Unfunny"],
  ["A-list", "C-list"],
  ["Tastes bad", "Tastes good"],
  ["Proud", "Shameful"],
  ["Common knowledge", "Expert knowledge"],
  ["Best", "Worst"],
  ["Mild", "Spicy"],
  ["Clean food", "Messy food"],
  ["Avant-garde", "Old fashioned"],
  ["Useful superpower", "Useless superpower"],
  ["Bad investment", "Good investment"],
  ["Delicious", "Disgusting"],
  ["High tech", "Low tech"],
  ["Global", "Local"],
  ["Easy to use", "Hard to use"],
  ["Long", "Short"],
  ["Best person ever", "Worst person ever"],
  ["Action movie", "Drama movie"],
  ["Bad habit", "Good habit"],
  ["Stable", "Unstable"],
  ["Fantasy", "Sci-fi"],
  ["Private", "Public"],
  ["Generous", "Greedy"],
  ["Specific", "Vague"],
  ["Guilty", "Innocent"],
  ["Cool hobby", "Uncool hobby"],
  ["Basic", "Extraordinary"],
  ["Tame", "Wild"],
  ["Normal", "Weird"],
  ["Emotional", "Logical"],
  ["Deep talk", "Small talk"],
  ["Bad advice", "Good advice"],
  ["Counter-culture", "Mainstream"],
  ["Easy to find", "Hard to find"],
  ["Play", "Work"],
  ["High energy", "Low energy"],
  ["Automatic", "Manual"],
  ["Exposed", "Hidden"],
  ["Flexible", "Rigid"],
  ["Cutting edge", "Obsolete"],
  ["Fragile", "Sturdy"],
  ["Insignificant", "Life-changing"],
  ["Local secret", "Tourist trap"],
  ["High maintenance", "Low maintenance"],
  ["Forgettable", "Legendary"],
  ["Extroverted", "Introverted"],
  ["Deep", "Shallow"],
  ["Messy", "Organized"],
  ["Customized", "Standard"],
  ["Handcrafted", "Poorly made"],
  ["Active", "Passive"],
  ["Cowardly", "Heroic"],
  ["Infinite", "Short"],
  ["Brand name", "Generic"],
  ["Imitation", "Original"],
  ["Solid", "Unstable"],
  ["Lenient", "Strict"],
  ["Metropolis", "Small town"],
  ["Harmless", "Lethal"],
  ["Useless info", "Vital info"],
  ["Amateurish", "Masterful"],
  ["Cheerful", "Gloomy"],
  ["Cluttered", "Minimalist"],
  ["Modern", "Outdated"],
  ["Loudly", "Quietly"],
  ["Irresistible", "Unappealing"],
  ["High brow", "Low brow"],
  ["Incompetent", "Skilled"],
  ["Colorful", "Monochrome"],
  ["Dynamic", "Stagnant"],
  ["Disposable", "Heirloom"],
  ["Common", "Elite"],
  ["Predictable", "Twisted"],
  ["Childish", "Sophisticated"],
  ["Mighty", "Weak"],
  ["Bitter", "Savory"],
  ["Draft", "Final product"],
  ["Trustworthy", "Unreliable"],
  ["Anxious", "Calm"],
  ["Classic", "Fad"],
  ["Arrogant", "Humble"],
  ["Coincidence", "Destiny"],
  ["Precise", "Vague"],
  ["Clumsy", "Graceful"],
  ["Boring", "Mind-blowing"],
  ["Aesthetic", "Ugly"],
  ["Profound", "Shallow"],
  ["Obscure", "World-renowned"],
  ["Innocent", "Provocative"],
  ["Elastic", "Stiff"],
  ["Darkness", "Light"],
  ["Cheap", "Priceless"],
  ["Eternal", "Temporary"],
  ["Hateable", "Lovable"],
  ["Galactic scale", "Small scale"],
  ["Fiction", "Non-fiction"],
  ["Essential", "Irrelevant"],
  ["Robust", "Unstable"],
  ["Attractive", "Repulsive"],
  ["Instantly", "Slowly"],
  ["Dry", "Soaked"],
  ["Dull", "Vibrant"],
  ["Grand", "Humble"],
  ["Easy", "Impossible"],
  ["Mandatory", "Optional"],
  ["Messy", "Sleek"],
  ["Calculated", "Unplanned"],
  ["Rural", "Urban"],
  ["Corporate", "Private"],
  ["Inoffensive", "Offensive"],
  ["Certain", "Doubtful"],
  ["Cold-hearted", "Warm-hearted"],
  ["Forgotten", "Timeless"],
  ["Cute", "Ugly"],
  ["Lavish", "Stingy"],
  ["Awkward", "Smooth"],
  ["Frail", "Unstoppable"],
  ["Noisy", "Serene"],
  ["Fragile", "Indestructible"],
  ["Spectacular", "Unimpressive"],
  ["Obvious", "Subtle"],
  ["Gentle", "Harsh"],
  ["Grim", "Optimistic"],
  ["Impactful", "Pointless"],
  ["Disposable", "Sustainable"],
  ["Blessed", "Cursed"],
  ["Coward", "Warrior"],
  ["Just", "Unfair"],
  ["Chaos", "Order"],
  ["Magnanimous", "Petty"],
  ["Expert", "Unskilled"],
  ["Abundant", "Rare"],
  ["Empty", "Full"],
  ["Immortal", "Mortal"],
  ["Cult classic", "Mainstream"],
  ["Modern", "Nostalgic"],
  ["Comfort food", "Exotic food"],
  ["Legend", "One-hit wonder"],
  ["Commercial", "Underground"],
  ["Creepy", "Cute"],
  ["Blockbuster", "Low budget"],
  ["Mystical", "Scientific"],
  ["Calming", "Stressful"],
  ["Hype", "Reality"],
  ["Masterpiece", "Overrated movie"],
  ["Cheap thrill", "Luxury experience"],
  ["New wave", "Old school"],
  ["Analog", "Digital"],
  ["Extroverted character", "Introverted character"],
  ["Boring superpower", "God-tier superpower"],
  ["Easy to kill", "Invincible"],
  ["Friendly alien", "Scary alien"],
  ["Bad ending", "Happy ending"],
  ["City life", "Rural life"],
  ["Maximalist", "Minimalist"],
  ["Salty", "Sweet"],
  ["Fine dining", "Street food"],
  ["Clean eater", "Messy eater"],
  ["Summer vibe", "Winter vibe"],
  ["Morning person", "Night owl"],
  ["Lazy", "Workaholic"],
  ["Follower", "Leader"],
  ["Doer", "Thinker"],
  ["Life mission", "Short-term goal"],
  ["Galactic savior", "Small town hero"],
  ["Dystopian", "Utopian"],
  ["High fantasy", "Low fantasy"],
  ["Abstract art", "Realistic art"],
  ["Silent", "Talkative"],
  ["Cool parent", "Strict parent"],
  ["Soulmates", "Unrequited love"],
  ["First date", "Gold wedding"],
  ["Mansion", "Small apartment"],
  ["AAA game", "Indie game"],
  ["Intellectual work", "Manual labor"],
  ["Hidden gem", "Tourist trap"],
  ["Private limo", "Public transport"],
  ["Budget travel", "First class"],
  ["E-book", "Paper book"],
  ["Black and white", "Technicolor"],
  ["Action flick", "Silent film"],
  ["Box office bomb", "Record breaker"],
  ["Based", "Cringe"],
  ["Hard liquor", "Soft drink"],
  ["Healthy snack", "Junk food"],
  ["Home cooked", "Takeout"],
  ["Savory lover", "Sweet tooth"],
  ["Bland food", "Spicy food"],
  ["Casual gamer", "Hardcore gamer"],
  ["4K", "Standard definition"],
  ["Laggy", "Smooth"],
  ["Buggy", "Polished"],
  ["Always online", "Offline"],
  ["Solo project", "Team effort"],
  ["Overpaid", "Underpaid"],
  ["CEO", "Entry level"],
  ["Expert", "Intern"],
  ["Dead-end job", "Dream career"],
  ["Deep conversation", "Small talk"],
  ["Calling", "Texting"],
  ["Commitment", "Ghosting"],
  ["Fling", "Marriage"],
  ["Best friend", "Stranger"],
  ["Blessed", "Unlucky"],
  ["Average Joe", "Chosen One"],
  ["Protagonist", "Sidekick"],
  ["Goat", "Legend"],
  ["Rookie", "Veteran"],
  ["Bad advice", "Wisdom"],
  ["Lie", "Truth"],
  ["Common knowledge", "Secret"],
  ["Fact", "Rumor"],
  ["Law", "Opinion"],
  ["Designer suit", "Ugly sweater"],
  ["Fast fashion", "Vintage"],
  ["Sneakers", "Stilettos"],
  ["Messy hair", "Perfect styling"],
  ["Evening gown", "Pyjamas"],
  ["Big cat", "Small cat"],
  ["Mutant", "Robot"],
  ["Laser gun", "Magic wand"],
  ["Vampire", "Zombie"],
  ["Ghost", "Werewolf"],
  ["Comedy", "Horror"],
  ["Romance", "Thriller"],
  ["Sci-fi", "Western"],
  ["Anime", "Live action"],
  ["Music", "Podcast"],
  ["Altruistic", "Selfish"],
  ["Forgotten", "Immortalized"],
  ["Betrayal", "Harmless lie"],
  ["Methodical", "Spontaneous"],
  ["Dogmatic", "Flexible"],
  ["Common sense", "Conspiracy theory"],
  ["Neglected", "Overprotected"],
  ["Tasteful", "Vulgar"],
  ["Ephemeral", "Lasting"],
  ["Fragile ego", "Unshakable confidence"],
  ["Global icon", "Local hero"],
  ["Pseudo-science", "Pure logic"],
  ["Guilty", "Vindicated"],
  ["Conscious", "Subconscious"],
  ["Chaos", "Harmony"],
  ["Exaggeration", "Understatement"],
  ["Explicit", "Vague"],
  ["Outdated tech", "Sci-fi tech"],
  ["Life or death", "Low stakes"],
  ["Soft-hearted", "Stone-cold"],
  ["Amateur", "Virtuoso"],
  ["Copycat", "Trendsetter"],
  ["Direct", "Passive-aggressive"],
  ["Brutally honest", "Polite"],
  ["Conformist", "Rebel"],
  ["Long-term investment", "Short-term pleasure"],
  ["Amicable split", "Messy breakup"],
  ["Hidden talent", "Public failure"],
  ["Extrovert's dream", "Introvert's nightmare"],
  ["Objective truth", "Unreliable narrator"],
  ["New money", "Old money"],
  ["Cheap plastic", "Solid gold"],
  ["Handmade", "Mass-produced"],
  ["Industrial", "Rustic"],
  ["Fragile", "Resilient"],
  ["Obscure law", "Universal right"],
  ["Sacred", "Taboo"],
  ["Optimist", "Pessimist"],
  ["Idealistic", "Realistic"],
  ["Believer", "Skeptic"],
  ["Bland", "Flavorful"],
  ["Odorless", "Pungent"],
  ["Rough texture", "Silky smooth"],
  ["Heavy", "Weightless"],
  ["Blinding", "Dim"],
  ["Instant spark", "Slow burn"],
  ["Clutter", "Sanctuary"],
  ["Garbage", "Work of art"],
  ["Coincidence", "Prophecy"],
  ["Luck", "Skill"],
  ["Flamboyant", "Modest"],
  ["Introverted city", "Party city"],
  ["High risk", "Safe bet"],
  ["Immature", "Old soul"],
  ["Forgivable", "Unpardonable"],
  ["Favorite", "Underdog"],
  ["Global phenomenon", "Niche interest"],
  ["Easy to lose", "Impossible to get rid of"],
  ["Forgettable face", "Unforgettable gaze"],
  ["Huge scandal", "Small lie"],
  ["Dry humor", "Slapstick"],
  ["Acquired taste", "Universal appeal"],
  ["Bittersweet", "Pure bliss"],
  ["Boring person", "Magnetic personality"],
  ["Bold", "Timid"],
  ["High-res masterpiece", "Low quality photo"],
  ["Block letters", "Cursive"],
  ["Scream", "Whisper"],
  ["Fluid", "Static"],
  ["Mind-bending twist", "Predictable plot"],
  ["Essential trade", "Useless degree"],
  ["Clueless", "Overqualified"],
  ["Intern", "Mentor"],
  ["Corporate drone", "Entrepreneur"],
  ["Burnout", "Peak performance"],
  ["Crowd pleaser", "Polarizing"],
  ["Humble brag", "Shameful admission"],
  ["Privacy", "Transparency"],
  ["Anonymous", "Famous"],
  ["Censored", "Unfiltered"],
  ["Analog life", "Metaverse"],
  ["Calculated success", "Dumb luck"],
  ["Fragile peace", "Total war"],
  ["Merciful", "Ruthless"],
  ["Sin", "Virtue"],
  ["Bad timing", "Perfect moment"],
  ["Light speed", "Slow motion"],
  ["Action-oriented", "Empty promises"],
  ["Generous", "Stingy"],
  ["Childhood dream", "Midlife crisis"],
  ["Beautiful lie", "Ugly truth"],
  ["Christmas morning", "Garbage day"],
  ["Anti-hero", "Boy scout"],
  ["Main storyline", "Side quest"],
  ["Confession", "Gossip"],
  ["Socially acceptable", "Socially awkward"],
  ["Necessary evil", "Pure evil"],
  ["Good for society", "Good for the individual"],
  ["Bullying", "Harmless prank"],
  ["Genius", "Madman"],
  ["Down to earth", "Pretentious"],
  ["Hard worker", "Wasted talent"],
  ["Dealbreaker", "Forgivable sin"],
  ["Ethical billionaire", "Mythical creature"],
  ["Total freedom", "Total security"],
  ["Strict discipline", "Total chaos"],
  ["Fair share", "Greed"],
  ["Childish", "Classic"],
  ["Profound masterpiece", "Useless art"],
  ["Culturally significant", "Forgotten fad"],
  ["Cluelessness", "Innocent mistake"],
  ["Honest truth", "Unnecessary rudeness"],
  ["Privacy", "Safety"],
  ["Modern progress", "Tradition"],
  ["Actually underrated", "Hyped up"],
  ["Brave", "Reckless"],
  ["Self-care", "Self-indulgence"],
  ["Appropriate", "Inappropriate"],
  ["Classy", "Flashy"],
  ["Destructive", "Revolutionary"],
  ["Deep", "Pseudo-intellectual"],
  ["Cheap trick", "Smart move"],
  ["Bureaucracy", "Common sense"],
  ["Heroic", "Self-serving"],
  ["Artistic liberty", "Historical inaccuracy"],
  ["Essential luxury", "Waste of money"],
  ["Guilty pleasure", "Mental health requirement"],
  ["Cruelty", "Tough love"],
  ["Delusional", "Optimistic"],
  ["Normal behavior", "Red flag"],
  ["Eccentric", "Insane"],
  ["Laziness", "Work-life balance"],
  ["Luck", "Talent"],
  ["Privilege", "Success"],
  ["No principles", "Open-minded"],
  ["Healthy boundary", "Selfishness"],
  ["Arrogance", "Confidence"],
  ["Constructive criticism", "Hate"],
  ["Gossip", "Public interest"],
  ["Cringey", "Inspirational"],
  ["Practical gift", "Thoughtless gift"],
  ["Necessary lie", "Uncomfortable truth"],
  ["Old fashioned", "Timeless"],
  ["Progressive", "Too far"],
  ["Over-prepared", "Under-prepared"],
  ["Irresponsible", "Spontaneous"],
  ["Blind obedience", "Loyalty"],
  ["Nostalgia", "Stagnation"],
  ["Criminal act", "Vigilante justice"],
  ["Mercy", "Weakness"],
  ["Fake personality", "Politeness"],
  ["Ambition", "Greed"],
  ["Controlling", "Parenting"],
  ["Free speech", "Hate speech"],
  ["Modern art", "Scam"],
  ["Authentic", "Manufactured"],
  ["AI generated", "Human touch"],
  ["Eco-friendly", "Virtue signaling"],
  ["Boring life", "Simple life"],
  ["Excess", "Luxury"],
  ["Gatekept", "Niche"],
  ["Echo chamber", "Popular opinion"],
  ["Attention seeker", "Rebel"],
  ["Minimalism", "Poverty aesthetic"],
  ["High risk", "Stupidity"],
  ["Cold", "Professional"],
  ["Casual", "Sloppy"],
  ["Aggressive", "Direct"],
  ["Flexible", "Wishy-washy"],
  ["Dead end job", "Underrated career"],
  ["Education", "Indoctrination"],
  ["Playing God", "Science"],
  ["Peer pressure from dead people", "Tradition"],
  ["Nationalism", "Patriotism"],
  ["Inherited", "Self-made"],
  ["Justice", "Revenge"],
  ["Martyrdom", "Sacrifice"],
  ["Privacy", "Secrecy"],
  ["Curiosity", "Nosiness"],
  ["Hobby", "Obsession"],
  ["Iconic", "Overexposed"],
  ["Dated", "Retro"],
  ["Bubble", "Trend"],
  ["Budget-friendly", "Cheap"],
  ["Equal", "Fair"],
  ["Dependency", "Safety net"],
  ["Narrative", "Truth"],
  ["Outdated advice", "Wisdom"],
  ["Empowerment", "Pandering"],
  ["Genius marketing", "Manipulation"],
  ["Marketing gimmick", "Organic"],
  ["Leader", "Tyrant"],
  ["Community", "Mob mentality"],
  ["Doom", "Future"],
];
